# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('to_user', models.CharField(max_length=100)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund_transfer',
            },
        ),
    ]
